<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/', 'middleware' => 'SentinelAdmin'), function () {

    Route::get('backends', ['as'=> 'admin.backends.index', 'uses' => 'BackendController@index']);
    Route::post('backends', ['as'=> 'admin.backends.store', 'uses' => 'BackendController@store']);
    Route::get('backends/create', ['as'=> 'admin.backends.create', 'uses' => 'BackendController@create']);
    Route::put('backends/{backends}', ['as'=> 'backends.update', 'uses' => 'BackendController@update']);
    Route::patch('backends/{backends}', ['as'=> 'backends.update', 'uses' => 'BackendController@update']);
    Route::get('backends/{id}/delete', array('as' => 'admin.backends.delete', 'uses' => 'BackendController@getDelete'));
    Route::get('backends/{id}/confirm-delete', array('as' => 'admin.backends.confirm-delete', 'uses' => 'BackendController@getModalDelete'));
    Route::get('backends/{backends}', ['as'=> 'admin.backends.show', 'uses' => 'BackendController@show']);
    Route::get('backends/{backends}/edit', ['as'=> 'admin.backends.edit', 'uses' => 'BackendController@edit']);

});